name: Github Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "triggered by: ${{ github.event_name }}"
          echo "branch: ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List of files in the repository
        run: |
          echo "This repo contains:"
          tree
